NASA-PDS/pds4-information-model

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Add the permissible value "Astrophysical" and its value meaning to the attributes
<Target_Identification.type> and <Target.Type>.
Value Definition: "The target is classified as of interest to the astrophysics community."

Issue #12 CCB_254_Add_Astrophysical_To_Targetype

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Deprecate the permissible value “Earth-based” from the enumerated list for the attribute <Instrument_Host.type>

Issue #14 CCB_244_Deprecate_Earth-based_from_Instrument_Host_type

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java

- writeDOMSchematron - Add namespace declaration for xsi
- ExportModels - Write Product XML Schema Label (No change to repository)

CCB258 Software_Updates

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPinsGlossary.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSpecification.java

1) WriteDOMSpecification
Convert to DOM attribute definitions - AttrDefn to DOMDefn
2) ProtPinsGlossary
Convert to DOM attribute definitions - AttrDefn to DOMDefn

Issue #32 DOMConv Deprecation_FinalCleanup WriteDOMSpecification

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

1) LDDDOMParser
Add DD_Associate_External_Class
deprecate validateAssociationCardinalities (AssocDefn)

Issue #40 CCB-256	Permissible_value_definitions_Ingest_LDD

---

model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml

190908 update of PDS4 Information Model V1D00 Database. The files are simply copied in, replacing the previous files.

Issue #54 190908_PDS4_Information_Model_V1D00_Database_Update - Part 1

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMCSVFile.java

1) LDDDOMParser -
modify code to handle the changes to DD_Associate_External_Class.
2) DOMRule -
Added ruleNameSpaceNC;
3) WriteDOMSchematron
Fix <sch:rule context="TBD_xpath">
4) WriteDOMCSVFiles
Remove "_DOM" from filename

Issue #70 CCB-256 Permissible_value_definitions_Ingest_LDD_Update

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

2a) UpperModel.pont -
Remove min/max occurrences from DD_Associate_External_Class
Add attribute_name to DD_Context_Value_List
2b) UpperModel.pins -
Remove min/max occurrences from DD_Associate_External_Class
Add attribute_name to DD_Context_Value_List
2c) DD11179.pins
Remove min/max occurrences from DD_Associate_External_Class
Add attribute_name to DD_Context_Value_List

#72 CCB-256 Permissible_value_definitions_Ingest_LDD_Update_Data

---

model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Remove CCB-256 from Build 10a after consulting with CCB reporter. More design and testing is required.

#75 CCB-256 Permissible_value_definitions_Ingest_LDD_Removal

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMAttr.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMDataType.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMProp.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMProtAttr.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ISOClass.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPontDOMModel.java

Fixed the calculation of class extensions and restrictions.
Update -v to write build version of the IM

#77 LDDTool_IMG_LDD_Brightness_Correction_Cristina

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

LDDTool bugfix - Problem: The value for IM Version Id in the XML Schema "import" file name was being set to "null".

Issue #79 LDDTool_XMLSchema_Fix_Null_In_Import

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

Update LDDTool to write the PDS4 Data Dictionary (DocBook) for multiple LDDS. Multiple LDDs can now be stacked to produce a combined PDS4 Data Dictionary.

#93 Multi_LDD_DataDictionary

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

Update LDDTool to write the PDS4 Data Dictionary (DocBook) for multiple LDDS; LDDTool Fix JAVA Package declaration; Remove debug flag.

Issue 95 Multi LDD DataDictionary Cleanup

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Sync up LDDTool version with Maven build version.
Resolves #127
BugFix

Sync up LDDTool version with Maven build version

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Add ability to specify many source products using an extension of Table_Delimited
Resolves #135
Refs CCB-220

CCB-220 Add ability to specify many source products via table.

---

model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Add the attribute dictionary_type to Ingest_LDD. The dictionary_type attribute provides the name of a dictionary category.
Resolves #137
Refs CCB-274

Add attribute dictionary_type to Ingest_LDD

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Reinstate Array_1D in the Information Model		
Resolves #148
Refs CCB-272

Reinstate Array_1D in the Information Model

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Add code to fail gracefully for deprecated -M command line argument
Resolves #154
Refs CCB-274

Add code to fail gracefully for deprecated -M argument

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Backout LDDTool change that allows multiple IM Versions. Postpone release to next build.
Resolves #179

Backout LDDTool change that allows multiple IM Versions

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMRule.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java

LDDTool: Deprecation Rule for Unit_Of_Wavenumber is being propagated to Spectral LDD with an error in the assert statement.
Resolves #197

LDDTool: Deprecation Rule being propagated to sch file with errors

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java

LDDTool: System exit in code terminates both IMTool/LDTool and the JAVA virtual machine. This aborts the MAVEN build.
Resolves #199

LDDTool: System exit in code aborts MAVEN build

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

LDDTool: System exit causing -v and -h command line options to fail.
Resolves #199

LDDTool: System exit causing -v and -h command line options to fail.

---

model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

CCB-289 Define new class Encoded_Audio to describe supplementary audio data products. Add a structure to the PDS Information Model for describing an audio file as a supplementary product.
Resolves #207
Refs CCB-289

CCB-289 Define new class Encoded_Audio to describe audio

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

IMTool: Remove read of environment variable JAVA_HOME.
Resolves #209

IMTool: Remove read of environment variable JAVA_HOME

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Separate the Option A (Alternate) from the alternate IM Version Id (1D00) in the command line.

Separate the Option A (Alternate) from the alternate IM Version Id

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetValueMeanings.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB-296	Duplicated value in enumerated value list of Product_Context /Internal_Reference /reference_type. Delete the duplicated value "investigation_to_facility" from the attribute Product_Context/Reference_List/Internal_Reference/reference_type.
Resolves #216
Refs CCB-296

Issue #216 - CCB-296 Duplicated value in Product_Context

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

LDDTool: Use a more generic IM Version flag (V) where you can specify any applicable IM Version (including the current), but it defaults to the current if this flag is not used.
Resolves #222
Refs CCB-85

Use a more generic IM Version flag (V)

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

CCB-289 Define new class Encoded_Audio to describe supplementary audio data products.
Cleanup - Add <Encoded_Audio> as an allowed component of <File_Area_Ancillary> and <File_Area_Browse>
Resolves #207
Refs CCB-289

CCB-289 Define new class Encoded_Audio - Cleanup

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMCSVFile.java

LDDTool - CSV files fail to escape double quotes. Scan text fields and escape each double quote with a double quote.
Resolves #280

Issue #280 - LDDTool - CSV files fail to escape double quotes

---

model-ontology/src/ontology/Data/config.properties

The update to address Issue #319 caused a problem with the config.properties file. This update restores the following lines to the file.
toolVersionId=${project.version}
buildDate=${buildNumber}
Resolves #319

Issue #319: Namespace Updates - add new namespace "multi"

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java

Add the LDD Version Identifier to the generated JSON file header.
Resolves #338

Issue #338 - Add the LDD Version Identifier to the generated JSON file.

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMAttr.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

The xpath is not valid in the schematron file. The definition of <Internal_Reference> is not complete in the XML Schema file.
The externally referenced class is now inherited with its original namespaces and with all components.
Resolves #369
Refs CCB-256

LDDTool Geometry Partitioning - XPath Invalid and Schema incomplete

---

model-ontology/src/ontology/Data/config.properties

Add the namespace "clipper" to the Namespace Registry and the config.properties file.
Namespace ID Requested: clipper
Discipline or Mission LDD? Mission-Specific Dictionary
Steward Organization Name: PDS CIS Node
LDD Steward Name: Trent Hare
LDD Steward Email: thare@usgs.gov
LDD Description: The Europa Clipper mission dictionary contains classes that describe aspects of the Clipper mission and related instruments.
Rationale for creation of new LDD: Support for the Europa Clipper mission. The dictionary is located here: https://github.com/pds-data-dictionaries/ldd-clipper
Resolves #374

Issue #374: Namespace - add "clipper"

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMProcessState.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/SchemaFileDefn.java

As a user I want to know the output of the tool after it completes execution. Suggested output:
Input:
PDS4 Flag: True
LDD Flag: True
IM Version: 1F00
Ingest LDD(s): /path/to/ldd-img/src/PDS4_IMG_IngestLDD.xml, /path/to/ldd-m2020/src/PDS4_M2020_IngestLDD.xml
Output:
PDS4_IMG_1F00_1830.JSON
PDS4_IMG_1F00_1830.JSON
PDS4_IMG_1F00_1830.csv
PDS4_IMG_1F00_1830.sch
etc.
Resolves #330

Issue #330 - Write summery of output of the tool after it completes execution.

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMProcessState.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

Clean up the output summary and added check for output directories - create if necessary
Resolves #330

Clean up the output summary and check for output directories

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB-340 - <Local_Internal_Reference>.<local_identifier_reference> cardinality
The request is to change the cardinality of the attribute <Local_Internal_Reference. local_identifier_reference> to [1,*]. This change allows a single object to be related to one or more objects.
Resolves #450
Refs CCB-340
For testing, see changed cardinality "local_identifier_reference 1..*"  in the Information Specification Document

CCB-340 - <Local_Internal_Reference>.<local_identifier_reference> card

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

This reverts commit b3eec13f031e7df0d508a3ce3a3709455fbcc7a6.
refs #434

Revert "Issue #434 ASCII_Date_Time_* - Schematron (#462)"

---

model-ontology/src/ontology/Data/config.properties

Issue #495 : [namespace-registry] add new namespace "apollo"
** Fix config.properties file header.
Add the namespace "apollo" to the Namespace Registry and the config.properties file.
@c-suh  [namespace-registry] add new namespace "apollo" #495
Resolves #495

Issue #495 : [namespace-registry] add new namespace "apollo" - fix

---

model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB-348 Add Units_of_Mass_Density as a unit of measure
Add Units_of_Mass_Density as a new subclass of Unit_of_Measure. The single value is unit kilograms per cubic meter. (kg/m**3)
Resolves #499
Refs CCB-348

CCB-348 Add Units_of_Mass_Density as a unit of measure

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Issue Title: Issue #596 - Stage the PDS4 Information Model Version 1.20.0.0 (1.K.0.0) for Update
Description: Stage the IMTool system for V1.20.0.0 to allow the implementation of approved SCRs and bug fixes.
*** For some reason the first pull did not include the changes. 
Resolves #596

Issue #596 - Stage the PDS4 Information Model Version 1.20.0.0 (1.K.0.0)

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFileLib.java

Added the file WriteDOMDDJSONFileLib, a refactored version of WriteDOMDDJSONFile that uses the org.json.simple library  to write the JSON file. The refactoring has been completed. The unit testing is about complete.
This Pull Request does not resolve #651 since the term mapping code must still be added. I just wanted to get the current code committed to the registry.
Refs CCB-351

Issue #651 Adds to default output JSON TermMap

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFileLib.java

Issue# 687 Sonatype - Suggested Modifications - WriteDOMDDJSONFileLib
Reference: Issue #670 Adds to default output JSON TermMap  (PR #671)  on 230810
Made several Sonatype suggested changes to module WriteDOMDDJSONFileLib
Resolves #687

Sonatype - Suggested Modifications - WriteDOMDDJSONFileLib

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ClassAttrPropClassification.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModelsCustom.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMCSVFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMCSVFileClassHier.java

Issue# 693  Fix code scanning alert - Container contents are never accessed 
ClassAttrPropClassification.java
ArrayList <String> lClassPropertyIdArr = new ArrayList <String> ();
Removed dead code.
Also modified the CSV file writer to use the newLine() method of BufferedWriter to write end-of-file consistent with System.lineSeparator().
Resolves #693

Fix code scanning alert - Container contents are never accessed #693

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Update schematron for agency urn:kari:kpds - Redux - Add apostrophes
Minor update: Add apostrophes around urn.
<sch:let name="urn_kari" value="'urn:kari:kpds:'"/>
<sch:let name="urn_kari" value="'urn:kari:kpds:'"/>
<sch:let name="urn_kari" value="'urn:kari:kpds:'"/>
Resolves #709

Update schematron for agency urn:kari:kpds - Redux - Add apostrophes

---

.github/workflows/branch-cicd.yaml
.github/workflows/stable-cicd.yaml
.github/workflows/unstable-cicd.yaml
model-dmdocument/pom.xml
model-lddtool/pom.xml
model-ontology/pom.xml
pom.xml
test/smoke-tests.sh

To avoid introducing untracked bugs into the build, added simple test script to build a couple dLDDs to ensure we aren't breaking anything.
NOTE: There are WAY better ways to do this, but this is a quick and dirty way to just get some sort of testing introduced here.
See CI/CD run. Note: Currently blocked by #733
Resolves #734

Add smoke tests to LDD CI to ensure LDDTool can execute successfully on push

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/AbstractGenerationPlugin.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Test changes made on [Update_to_Support_for_OpenJDK17Try2](https://github.com/NASA-PDS/pds4-information-model/tree/Update_to_Support_for_OpenJDK17Try2) on branch `Issue714-LDDTool-Tests` to determine if changes fix problems noted in #714

Merge Update_to_Support_for_OpenJDK17Try2 into Issue714-LDDTool-Tests

---

.github/workflows/stable-cicd.yaml
pom.xml

Merge to resolve [this issue in roundup-action](https://github.com/NASA-PDS/roundup-action/issues/136). Note: not roundup-related, but that's where the issue lives 😇 
See sandbox for:
- [CI run](https://github.com/nasa-pds-engineering-node/pds4-information-model/actions/runs/8727498092)
- [Sandbox website](https://nasa-pds-engineering-node.github.io/pds4-information-model/)
- [roundup-action#136](https://github.com/NASA-PDS/roundup-action/issues/136)

Makes sure website gets published

---

model-dmdocument/src/site/site.xml
model-lddtool/src/site/site.xml
model-ontology/src/site/site.xml
pom.xml
src/site/site.xml

Update site generation per maven site plugin ugprade
```
$ mvn install site site:stage
```
Resolves #761

Update site generation per maven site plugin ugprade

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj
model-ontology/src/ontology/Data/dd11179.pont
model-ontology/src/ontology/Data/dd11179.pprj

Never finished CCB-325 lien for browse and ancillary
Add the existing Encoded_Video class to File_Area_Ancillary and File_Area_Browse. The Encoded_Video class had been previously added to File_Area_Observational and File_Area_Observational_Supplemental. This change completes a prior approved change request. 
Also performed a partial back-out of the context Investigation prototype. Simply removed the association in protege. The classes and attribute were not deleted. 
-   terse_description
-   Alias_Index
-   Acronym_Index 
-   Mission_Phase
-   Author_List, Editor_List, and Collaborator_List in Modification_Detail
The PDS4_PDS_1N00.xsd file (renamed PDS4_PDS_1N00.xsd.txt) has been attached. For verification check File_Area_Ancillary -  line 1374 and File_Area_Browse - line 1425.
Resolves …

Complete additional updates for JIRA-CCB-325 (NASA-PDS/PDS4-CCB#18) per `Encoded_Video` class

---

model-lddtool/src/site/xdoc/install/index.xml.vm

Fix broken download link

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-lddtool/src/test/java/cucumber/LddToolRunner.java
model-lddtool/src/test/java/cucumber/ValidateStepDefs.java
model-lddtool/src/test/resources/features/validate.feature
model-lddtool/src/test/resources/github753/PDS4_MARS2020_IngestLDD.xml
model-lddtool/src/test/resources/github829/ORB_35_STAR_SCANNER.xml
model-lddtool/src/test/resources/github852/PDS4_LCROSS_IngestLDD_1000.xml
model-lddtool/src/test/resources/github852/PDS4_LCROSS_IngestLDD_1100.xml
model-lddtool/src/test/resources/github852/lcross_nir2_cal_20090622162743896.xml

- [Update handling of exit codes](https://github.com/NASA-PDS/pds4-information-model/commit/4c822425b35e2b29613199790e1ae5bd5fae057f)
- [Update test cases to be more strict, which now fail](https://github.com/NASA-PDS/pds4-information-model/commit/760f49da2c42234076fa56804a7e6123aa435f0d) - commented out failing use cases until we can run this to ground in validate
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests
Resolves #857 
Refs #852 
Refs #856

Update handling of exit codes 
