model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java
model-ontology/src/ontology/Data/config.properties

Problem: Input of two or more LDDs to LDDTool (an LDD stack) results in null pointer exception.
Analysis: LDDTool tried to find LDD nameSpaceID for "Import" statements in configured PDS4 nameSpaceID array.
Solution: Use masterAllSchemaFileSortMap instead of masterSchemaFileSortMap. The latter includes only those nameSpaces to be written to XML Schema file.

Issue #4 - DOMConv_UnitTesting_LDDDOMParser_Cart_Geom_abort

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ISO11179DOMMDR.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPinsDOM11179DD.java

Problem: During test of the new DOM Dictionary (Protege 11179dd.pins) file several classOrder values were found to be set to the default (9999). This resulted in an XML Schema with several validation errors.
Solution: Create a DOM version of ProtPins11179DD, namely ProtPinsDOM11179DD. Use the Property Id instead of the Attribute ID to create the dictionary element identifier.

Issue-#7--DOMConv_UnitTesting_PINS_Test_classOrder

---

model-ontology/src/ontology/Data/dd11179.pins

Change data type of attribute <doi> to ASCII_DOI.
doi in Citation_Information
doi in Document
doi in External_Reference
doi in Source_Product_External
Install the new dd1179.pins file.
This file contains the definitions of all attributes in the PDS4 Information Model.
The difference between this, the DOM version and the original MOF version is that the property identifiers have an additional suffix to ensure uniqueness.

Issue-#9 CCB-237 - Change Attribute doi to Data Type ASCII_DOI

---

model-ontology/src/ontology/Data/dd11179.pins

Make the attribute <Science_Facets.wavelength_range> nillable. This change allows a mission/project to enforce the inclusion of a value for <Science_Facets.wavelength_range> at the local governance level, even when no value is applicable.

Issue #17 CCB-252_Make_Science_Facets_wavelength_range_nillable

---

model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

- Define a new data type UTF8_Text_Collapsed
- Change the data type of the attribute <External_Reference.reference_text> from ASCII_Text_Preserved to UTF8_Text_Collapsed.
-- <External_Reference.reference_text> is inherited by <External_Reference_Extended.reference_text>
- This change allows accented and other characters which are very common in names.

Issue #21 CCB-266-Change_Data_Type_of_External_Reference_reference_text

---

model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Add Units_of_Force as a unit_of_measure_type. This change is required in order to capture how hard the M2020 arm pre-load tool is pushing on the surface before beginning a drilling operation.

Issue #25 CCB-253-Add_Units_of_Force_as_a_unit_of_measure

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DeprecatedDefn.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XMLDocParserDomMDPTNConfig.java

IMTool/LDDTool Conversion from MOF to DOM model; Final cleanup; Focus on DeprecatedDefn and similar methods.
1) XMLDocParserDomMDPTNConfig.java 57  AttrDefn
Deprecate - 	AttrDefn lAttrMaster;
2) DeprecatedDefn
InfoModel -> DOMInfoModel
3) WriteSchematronRulesPins - Validated deprecate
deprecate - Wrote MODEL_RULES file. Initated Upper_Model standard rules in .pins file
4) GetDOMModel
deprecate GenSchematronRules genSchematronRules = new GenSchematronRules ();
deprecate genSchematronRules.genSchematronRules();
5) MasterDOMInfoModel.java 1457, 1475 AttrDefn, PDSObjDefn
deprecate getPossibleRestrictedAttribute
deprecate getPossibleRestrictedAssociation
deprecate clonePDSObjDefnArrayList
6) DOMInfoModel.java 149, 154, 160, 161, PermValueDefn, PDSObjDefn - Partially Done. - Wait on …

Issue #36 DOMConv Deprecation_FinalCleanup - DeprecatedDefn

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModelDoc.java

IMTool/LDDTool Conversion from MOF to DOM model; Final cleanup; Remove MOF methods from ExportModel
1) ExportModels
a) Remove MOF methods
Removed all
if (mofFlag) { ... }
b) RegConfig.java - set flag to false.
if (mofFlag) {
RegConfig regConfig = new RegConfig ();
regConfig.writeRegRIM(DMDocument.sTodaysDate);
regConfig.writeRegRIM3(DMDocument.sTodaysDate);
regConfig.writeRegRIM4(DMDocument.sTodaysDate);
}
c) Write11179RDFFile.java replace with WriteDOM11179DDRDFFile
d) AssocClassDefn.java - Deprecate AssocClassDefn
replace WriteStandardIdExtract with WriteDOMStandardIdExtract
2) GetDOMModelDoc - remove calls to ProtPontModel
else if (lModelInfo.type.compareTo("ProtPontModel") == 0) {
lModelInfo.objectid  = new ProtPontModel ();
ProtPontModel lobjectid  = (ProtPontModel) …

Issue #42 DOMConv Deprecation_FinalCleanup - ExportModels

---

model-ontology/src/ontology/Data/UpperModel.pins

190908 update of PDS4 Information Model V1D00 Database. The files are simply copied in, replacing the previous files.
Part 1 was a test for the configuration file, MDPTNConfigClassDisp.xml.
Part 2 is a test for the object ontology .pins file, UpperModel.pins.
Process:
a) Copy source file.
b) Past source file, relace repository file

Issue #56 190908_PDS4_Information_Model_V1D00_Database_Update - Part 2

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMRule.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPontDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMRDFOWLFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteLODSKOSFileDOM.java

1. DOMInfoModel
Deprecate finishCloneAttr (AttrDefn)
Deprecate   static TreeMap <String, IndexDefn> cdAttrMap = new TreeMap <String, IndexDefn>();
static TreeMap <String, IndexDefn> decAttrMap = new TreeMap <String, IndexDefn>();
2. LDDDOMParser
Remove AssocDefn (commented)
3. WriteDOMDDJSONFile
Convert to DOM
static TreeMap <String, IndexDefn> cdAttrMap = new TreeMap <String, IndexDefn>();
static TreeMap <String, IndexDefn> decAttrMap = new TreeMap <String, IndexDefn>();
4. WriteLODSKOSFileDOM
Convert to DOM
static TreeMap <String, IndexDefn> cdAttrMap = new TreeMap <String, IndexDefn>();
static TreeMap <String, IndexDefn> decAttrMap = new TreeMap <String, IndexDefn>();
5. WriteDOMRDFOWLFile
Dependent on IndexDefn
public  void printPDDPCD (PrintWriter prDDPins) {
public  void …

Issue #66 DOMConv_Deprecation_FinalCleanup_Continued

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMDataType.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

LDDTool general cleanup
MasterDOMInfoModel - move test on testTrue outside of loop
DOMDataType - setting this.nsTitle is not needed since it is set by this.setIdentifier
DMDocument - added "exit" message
XML4LabelSchemaDOM - get info for XML schema namespace declaration - add pds (common) as default
WriteDOMSchematron - get info for XML schema namespace declaration - add pds (common) as default
LDDDOMParser - added helpful comments.

Issue #81 LDDTool_XMLSchema_Fix_Null_In_Import_Cleanup

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

LDDTool aborts while processing CTLI IngestLDD file. The reported error is Exception in thread "main" java.lang.ClassCastException: DOMAttr cannot be cast to DOMClass. Changed test for class name from MOF "AttrDefn" to DOM "DOMAttr".

Issue #91 Fix LDDTOOL CTLI IngestLDD Abort

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

The list of valid values for the <type> attribute in the <Observing_System_Component> class should be reduced to: Instrument, Host, Literature Search and Telescope. All other existing values should be deprecated.
Resolves #103
Refs CCB-138

CCB-138 Fix mismatch between object types in <Observing_System_Component> class

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

Susie Slavney reported that LDDTool aborted when using a short filename for the Ingest_LDD file. The problem was in writing the Dictionary Stack to the XML Schema document. All stack entries are truncated to 73 characters. In this case the entry was less than 73 characters.
Resolves #111

LDDTool aborts on short filename

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Validates that no class defined with <element_flag> set to "true" may be a component at any level of another class with <element_flag> set to "true". This is part 3 of CCB-204, a set of software updates to LDDTool.
Resolves #113
Refs CCB-204

Validate that there are no nested Exposed classes

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

An attribute that is defined as "nillable" must be a required attribute of at least one class. - Part 4 of CCB-204
Resolves #122
Refs CCB-204

Nillable attribute must be a required attribute of one class

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

Nillable attributes defined in IngestLDD are defined as nillable in XML Schema, but are not declared nillable when used within a class.
Resolves #125
Bugfix

Nillable attributes are not declared nillable in class definitions.

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-lddtool/src/main/assembly/tar-assembly.xml
model-lddtool/src/main/assembly/zip-assembly.xml
model-ontology/src/ontology/Data/config.properties

Similar to other config information and how we tend to handle versioning in
other tools, moved the software version to a config file that uses the Maven
version automatically.
One less thing we have to change at build time.
Resolves #124

Update tool versioning to move to config file

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetValueMeanings.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Add reference_types for Product_Ancillary
1. For attribute:	Product_Ancillary/Context_Area/Investigation_Area/Internal_Reference/reference_type
ancillary_to_investigation - The ancillary data product is associated to an investigation
2. For attribute: Product_Ancillary/Context_Area/Target_Identification/Internal_reference/reference_type
ancillary_to_target - The ancillary data product is associated to a target
3. For attribute: Product_Ancillary/Reference_List/Internal_Reference/reference_type
ancillary_to_document - The ancillary data product is associated to a document
Resolves #133
Refs CCB-271

Add reference_types for Product_Ancillary

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/SchemaFileDefn.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

Deprecate -M command line option (indicates Mission LDD) for LDDTool. Replaced by the attribute dictionary_type in Ingest_LDD. The dictionary_type attribute provides the name of a dictionary category.
Resolves #144
Refs CCB-274

Add attribute dictionary_type to Ingest_LDD - Remove -M Option

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

Change the error message reported when an attribute that is defined as "nillable" is not a required attribute of at least one class.
Resolves #146
Refs CCB-204

Change the error message reported for "nillable" attribute error.

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

The Common (pds) schema is missing <DD_Associate_External_Class> in the <DD_Class> definition.
Resolves #130
Refs CCB-256

BugFix - Add <DD_Associate_External_Class> to <DD_Class> definition

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Add schematron rule to validate for matching <axes> and Axis_Array Specifications.
Resolves #152
Refs CCB-279

Mis-Matched <axes> and Axis_Array Specifications

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

LDDTool does not handle "unbounded" maximum cardinality in Choice blocks correctly.
When defining a Choice block in Ingest_LDD, the character "*" is used as a value to represent an unlimited upper bound for cardinality. This value needs to be converted to "unbounded" when writing to an XML SChema file. This error only occurred in the case of the Choice block.
Resolves #180

LDDTool does not handle "unbounded" maximum cardinality correctly

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

Reclassify CCB-204 messages that LDDTool writes to the output log. Three validation checks performed by LDDTool current write ERROR messages to the output log when the checks fail. The changes follow.
- No attribute should be named "unit", "units", "unit_of_measure", or similar, or end in any of those strings.
ERROR   The attribute names 'unit', 'units', 'unit_of_measure' cannot be used.
Change ERROR to WARNING and change the message.
- No class defined with <element_flag> set to "true" may be a component at any level of another class with <element_flag> set to "true".
ERROR    An exposed class cannot be nested within another exposed class.
Change ERROR to WARNING and change the message.
- An attribute that is defined as "nilable" must be a required attribute of at least one class.
ERROR …

Reclassify CCB-204 messages that LDDTool writes to the output log.

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

Update one  CCB-204 related message that LDDTool writes to output log.
-   Change message text to "An exposed class was found nested within another exposed class. Nested exposed classes should only be present if there is a specific requirement to expose the additional class."
Resolves #179
Refs CCB-204

Update one  CCB-204 related message that LDDTool writes to output log

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Fixed bug with LDDTool command-line option processing that skipped Ingest_LDD file names under in certain situations.
Resolves #179

Bugfix - Cleanup LDDTool change to backout multiple Versions - 2

---

model-lddtool/src/site/xdoc/install/index.xml.vm

**Summary***
Trivial changes to see how easy this all works.  I know I'm using `master` -> `master` here, so I expect to get yelled at for not branching first.
**Test Data and/or Report**
- This is a documentation-only change.
- I built the site artifacts using the `mvn` scripts supplied in `util/`.  It worked as expected.
**Related Issues**
I don't think anyone had an issues this addresses.

Add a shortcut for setting JAVA_HOME on MacOS and missing PATH example

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java

LDDTool: Cleanup output log messages to use consistent formatting and remove unnecessary messages. Phase 2, focused on including the LDD Parser error, warning, and info messages. Also cloned code for combined LDD JSON file to LDDTool.
Resolves #85

LDDTool: Cleanup output log messages to use - Phase 2

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

LDDTool requires one class with (element_flag = true), even when no classes defined. The code was fixed to throw the error only when the number of classes are greater than zero. 
Resolves #188

LDDTool: requires one class with (element_flag=true), even when no classes are defined

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

LDDTool: Two choice blocks defined in the ingest file gets merged into one block in the schema
Resolves #192

LDDTool: Fixed problem where two choice blocks were being merged into one

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

CCB-294 Add enumerated value to Units_of_Pixel_Resolution_Angular. The request is to add the permissible value “HA/pixel” and its value meaning to the attribute <Units_of_Pixel_Resolution_Angular. unit_id>, a type of Unit_Of_Measure. This change supports providing resolution in the solar hour angle coordinate. This change request is reasonable.
Resolves #218
Refs CCB-294

CCB-294 Add enumerated value to Units_of_Pixel_Resolution_Angular

---

model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Fix the problem causing the following warning messages
WARNING Class disposition was not found - Y UpperModel.0001_NASA_PDS_1.Cartography_Group 1M #nm ns
WARNING Class disposition was not found - Y UpperModel.0001_NASA_PDS_1.Rings 1M #nm ns
WARNING Class omitted from build - Class Identifier:0001_NASA_PDS_1.pds.Schematron_Rule
WARNING Class omitted from build - Class Identifier:0001_NASA_PDS_1.pds.Schematron_Assert
Resolves #225

IMTool - Cleanup warning messages

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

LDDTool: update LDD attribute checking to only check for "type" and "_type". The ERROR attributed to “subtype” is itself an error. It is only of type “type” if it ends in “_type” (or is only “type”). A subType should not be checked.
Resolves #230
Refs CCB-204

LDDTool: update LDD attribute - check only for "type" and "_type"

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

LDDTool: erroneously replaces TBD values with null in JSON output. When running LDDTool to produce JSON output, <definition> values in <DD_Attribute> that start with TBD are replaced with null in the output.
Since LDDTool uses "TBD" as an equivalent for "null" to indicate that a user value was not provided, the solution is to prepend a user-supplied "TBD" with "_" resulting in "_TBD".
Resolves #227

LDDTool: erroneously replaces TBD values with null in JSON output

---

model-ontology/src/ontology/Data/config.properties

LDDTool: uses the wrong version of XSD when referencing IMG dictionary. Updated config.properties file.
Resolves #229

LDDTool: uses wrong version of XSD when referencing IMG dictionary

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

The DD_Associate_External_Class schematron rule to test for valid values includes the attribute name twice in the rules error message. Removed code that duplicated the second occurence of the attribute name.
Resolves #235
----- REMOVE -----
Title ^^^^ above ^^^^ should follow good commit message best practices wherever possible.
A properly formed git commit subject line should always be able to complete the following sentence:
If applied, this commit will <your subject line here>
----- REMOVE -----
**Summary***
Brief summary of changes if not sufficiently described by commit messages.
**Test Data and/or Report**
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests
**Related …

Incorrect error messages for DD_Associate_External_Class

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

DocBook generation does not work from any file system location. Added code to check for the specified directory and creates the directory if needed.
Resolves #170

LDDTool: DocBook generation does not work from any file system location

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

The IM contains several generic vector classes that appear to be unused.
Deprecate the following vector classes in the core information model:
Vector
Vector_Component
Vector_Cartesian_3
Vector_Cartesian_3_Acceleration
Vector_Cartesian_3_Position
Vector_Cartesian_3_Velocity
Bugfix  - Add "1G00" to alternateIMVersionArr
Resolves #252
Refs CCB-304
----- REMOVE -----
Title ^^^^ above ^^^^ should follow good commit message best practices wherever possible.
A properly formed git commit subject line should always be able to complete the following sentence:
If applied, this commit will <your subject line here>
----- REMOVE -----
**Summary***
Brief summary of changes if not sufficiently described by commit messages.
**Test Data and/or Report**
One of the following should be included here:
* …

CCB-304 - Cleanup unused Vector classes in IM before 2.0.0.0

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Modify the definition of the attribute <external_source_product_identifier>. The referenced section number needs to be corrected by changing the section 2.6.1.2 --> E.2.6.1.2.
Resolves #253
Refs CCB-313

Modify the definition of external_source_product_identifier

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Definition of <external_source_product_identifier> refers to non-existent documentation.
In the definition of <external_source_product_identifier> modify the sentence: "For guidelines on the construction of this identifier, refer to section 2.6.1.2 of the Data Provider's Handbook." to read "For guidelines on the construction of this identifier, refer to section E.2.6.1.2 of the Data Provider's Handbook."
Resolves #275
Refs CCB-313

Definition of <external_source_product_identifier> Update

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

LDDTool - The LDD versionId list in the Data Dictionary Document introduction does not contain valid versionIds. Fix the LDD versionId list to use the versionId from the IngestLDD file. The versionIds were being set to 0.0.0.0.
Expected: Generated from Information Model Version 1.15.0.0 on Mon Dec 28 16:39:10 EST 2020Contains namespace ids: pds v1.15.0.0, cart v1.9.3.3, geom v1.7.0.0, img v1.6.1.0, img_surface v1.1.1.0, msn v1.1.0.0, msn_surface v1.1.0.0, proc v1.1.0.0, rings v1.8.0.0Mon Dec 28 16:39:10 EST 2020
Resolves #277

LDDTool - Fix LDD Version ID list in Data Dictionary Document Intro

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteCoreXMLSchemaLabel.java

LDDTool generated LIDs for XML Schema Label Products do not contain IM or LDD Version Ids. Add the IM and LDD version ids.
Example original LID : urn:nasa:pds:system_bundle:xml_schema:orex-xml_schema
Example requested LID : urn:nasa:pds:system_bundle:xml_schema:orex-xml_schema_1.15.0.0_1.1.0.0
Resolves #283

LDDTool LIDs for XML Schema Products do not contain IM or LDD VIDs

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

The request is to add the permissible value 'ns' to the 'Units_of_Time' Unit_Of_Measure. This change will allow the RIMAX experiment on Mars 2020 to use nanoseconds as a unit of measure for their PDS4 labels.
Resolves #285
Refs CCB-319

CCB-319 - Add 'ns' – The abbreviated unit for 'Units_of_Time'

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Add the permissible value ‘W/m**2/sr/nm/(DN/s)’ to the ' Units_of_Misc' Unit_Of_Measure. This change will allow the M2020 mission to store calibration parameters in the label with an appropriate unit designation.
Resolves #286
Refs CCB-320

CCB-320 - Add 'W/m**2/sr/nm/(DN/s)' under Units_of_Misc

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

LDDTool - Throw a WARNING message when enumeration_flag = false but enumerations are specified. Also, throw a WARNING message when enumeration_flag = true but there are no enumerations specified.
Resolves #266

LDDTool - Throw WARNING when enumeration_flag = false but enumerations are specified

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetValueMeanings.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

No <reference_type> values are defined in DD_Attribute or DD_Class contexts.
Add the permissible values “class_to_image” and “class_to_document” to the attribute <DD_Class.Internal_Reference.reference_type> and the values “attribute_to_image” and “attribute_to_document” to the attribute <DD_Attribute.Internal_Reference.reference_type>.
Resolves #257
Refs CCB-302

CCB-302 - No <reference_type> values defined in DD_Attrib or DD_Class

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java

Update JSON output to include dependencies in output.
From the current JSON output, there is no way of determining dependencies for the LDDs until you parse the JSON. We should add something to the top of the JSON that includes that.
Resolves #293

LDDTool - Update JSON output to include dependencies in output

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java
model-ontology/src/ontology/Data/dd11179.pins

Modify the value meanings of the permissible values of <rule_type> to be more meaningful.
Assert - Assert rules are usually used for error detection. If the test fails, the associated message is displayed.
Assert Every - An Assert Every rule is an extension to the Assert rule that uses the "every" qualifier to indicate every member of a defined set.
Assert If - An Assert IF rule is an extension to the Assert rule that limits the rule to the "if-then" pattern.
Report - Report rules are usually used for information-gathering. If the test succeeds, the associated message is displayed.
Resolves #296
Refs CCB-311

CCB-311 - Value meanings for <rule_type> permissible values rewritten

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

Make the Line Feed (LF) character an allowed record delimiter.
Add "Line-Feed" as a permissible Value to the attribute <record_delimiter> and with value_meaning, "Records in the * are delimited by ASCII line-feed (0x0A)".
This should apply in the following contexts:
Checksum_Manifest
Stream_Text
Table_Character (and its subclasses)
Table_Delimited (and its subclasses)
Resolves #299
Refs CCB-264

CCB-264 Make the Line Feed (LF) character an allowed record delimiter

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Apparently deprecated units of measure are not actually deprecated.
Units of measure that are indicated as being deprecated are not actually deprecated. Add schematron rules to test for and flag an error for deprecated units of measure in a label attribute. 
Resolves #255
Refs CCB-300

CCB-300 - Deprecated units of measure are not actually deprecated

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java

LDDTool does not generate the correct namespace for PSA dictionaries.
The primary namespace declaration in the generated Schematron file a) used the PDS namespace prefix and b) included the "mission" term. To omit the "mission" term, a new option was provided (-d).
Resolves #301

Issue #301 - LDDTool does not generate the correct namespace for PSA

---

model-ontology/src/ontology/Data/dd11179.pins

Modify the value meanings of the permissible values of <rule_type> to be more meaningful.
Assert - Assert rules are usually used for error detection. If the test fails, the associated message is displayed.
Assert Every - An Assert Every rule is an extension to the Assert rule that uses the "every" qualifier to indicate every member of a defined set.
Assert If - An Assert IF rule is an extension to the Assert rule that limits the rule to the "if-then" pattern.
Report - Report rules are usually used for information-gathering. If the test succeeds, the associated message is displayed.
Resolves #296
Refs CCB-311

CCB-311 - Redux - Value meanings changed again.

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Remove "PDS3" from Stream_Text as an allowable string in Product_Bundle.
For this ticket, this would be only pushing a rule for Product_Bundle to NOT allow "PDS3".
The request is to add a Schematron rule that would disallow "PDS3" to be used as a standard value for the attribute <Stream_Text.parsing_standard_id> in the context of <Product_Bundle.File_Area_Text.Stream_Text>. When the bundle’s <File_Area_Text> is used to describe a README file the standard value for the attribute <Stream_Text.parsing_standard_id> should be chosen from the set {“7-Bit ASCII Text”,”UTF-8 Text”}.
Resolves #250
Refs CCB-315

CCB-315 - "PDS3" is an allowed parsing standard for Bundle doc file

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

CCB-204 - Define and enforce best practices for discipline and project dictionaries.
1) Local dictionary attributes named "type" or with names ending in "_type" must have permissible value lists.  In the pds: and discipline namespaces these attributes are associated with search facets as well as value validation.
Reclassify CCB-204 messages written to the output log.  DDWG voted to change the error message to a warning for "type" attribute validation.
Resolves #179
Refs CCB-204

CCB-204 - Item 1 - Type Attribute Check - Reclassify message as Warning

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

LDDTool does not generate the complete "All LDD" version of the WebHelp PDS4 Data Dictionary Document.
This bug was caused by a prior fix. The bug caused all the specified LDD content to be ignored. The bug fix causes all of the LDD content to be included.
Resolves #312

Issue #312 - LDDTool fails to create "All LDD" version of the WebHelp DD

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

LDDTool does not generate the correct namespace for PSA dictionaries.  Make the update to the XML Schema writer.
Resolves #301

LDDTool should write the PSA namespace without Mission

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMClass.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

LDDTool needs to allow class/attributes defined using DD_Associate_External_Class to be inherited. The class and attribute defined using DD_Associate_External_Class must be defined within context (e.g., xpath) in order to be inherited by one or more sub classes.
Resolves #324

An LDD developer desires to inherit a class defined in an external namespace

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

LDDTool outputs an invalid schema that includes an Import statement for the LDD being built. The bug has been fixed.
Resolves #328

Issue #328 - LDDTool outputs an invalid schema

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

LDDTool does not generate the complete "All LDD" version of the PDS4 Data Dictionary Document. This bug was caused by a prior fix. 
Resolves #256

LDDTool does not generate the complete "All LDD" PDS4 DD

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

Invalid output schema when trying to set an Internal_Reference reference_type value set. The following procedure was not being performed to validate and set the values of min and max occurrences.  The procedure is now being performed.
validateAssociationCardinalities (lMinimumOccurrences, lMaximumOccurrences
Resolves #331

Invalid output schema when trying to set an Internal_Refererence reference_type value set

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

CCB-328 - Inconsistency in <title> type definition  - In the IM change the data type for the following attributes to UTF8_Short_String_Collapsed.
1. title in Identification_Area
2. title in Composite_Structure
3. title in Property_Map
4. title in Property_Maps
5. title in Terminological_Entry_SKOS
Resolves #339
Refs CCB-328

CCB-328 - Inconsistency in <title> type definition

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMAttr.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMClass.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ISOClassOAIS11179.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

Prototype a discipline LDD for SKOS Related Permissible Value Query Models.
The QM_SKOS_Related_Elements Local Data Dictionary (LDD - namespace: “qmsre”) was defined to allow similar permissible (standard) values to be related formally using SKOS relations.
For each PDS4 attribute for which permissible values are to be related, a <DD_Class> is created. Each class in turn uses <DD_Associate_External_Class> to reference a target PDS4 attribute and its PDS4 class. Within the attribute’s <DD_Permissible_Value> the targeted attribute’s value is specified. Each value to be related is then included in a <Terminological_Entry>.  The attribute’s original value is also included in a “preferred” terminological entry.
See attached IngestLDD and output JSON file (files extensions changed to .txt.) …

Issue #361 - LDDTool - Query Model LDD for SKOS Related Values

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMMsgDefn.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

LDDTool Geometry Partitioning Task - Remove the reported error "At least one class must be defined as an xs:Element. (<element_flag> set to true)". Since the dictionary is partitoned, only one partition is required to have an <element_flag> set to "true".
Resolves #324

Issue #324 - LDDTool Geometry Partitioning Task - Remove Error

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

The LDDTool -d command line option is not visible in the command line listing. This option omits the term mission from the namespace of a dictionary whether the dictionary is at the Discipline or the Mission level.
Resolves #301

Issue #301 - LDDTool -d command line option not visible.

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

Modify the LDDTool schematron rule generator to prepend the title of all inherited-by classes to the xpath of the inherited class.
Resolves #367
Refs CCB-256

LDDTool Geometry Partitioning - Prepend Inherited-By class to XPath

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

The versionId for Product_XML_Schema label is set to 1.0. It should instead be set to 1.22, the value to be used for IM Version 1.16.0.0.
Resolves #371

Issue #371 - VersionId for Product_XML_Schema label is wrong

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMRule.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java

When using the DD_Associate_External_Class to create an Abstract class, a rule should not be created to validate any attribute of the abstract class. A rule will be created for the attributes of the subclass of the abstract class.
Resolves #369
Refs CCB-256
**Summary***
Removed the code that included Schematron rules for the abstract classes Body_Identification_Base and Frame_Identification_Base. 
**Related Issues**
Continue to debug the new code using DD_Associate_External_Class for the Geometry LDD Partitioning task. The attached includes the Geometry LDD partitioned into two parts, the run command, and before and after schematron files.
[RemoveAbstractClassIssueIssue369.zip](https://github.com/NASA-PDS/pds4-information-model/files/6736956/RemoveAbstractClassIssueIssue369.zip)

Issue #369 - Remove Body_Identification_Base from SCH File

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOM11179DDPinsFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

IMTool/LDDTool Cleanup - Remove masterSchemaFileSortMap
IMTool/LDDTool still attempts to process dLDD ingested into Protege. The masterSchemaFileSortMap was used to capture dLDDs that were ingested into the IM Protege DB. Since dLDDs are no longer ingested, the map can be replaced by masterPDSSchemaFileDefn.
Resolves #378

Issue #378 - IMTool/LDDTool Cleanup - Remove masterSchemaFileSortMap

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java

Issue with DD_Associate_External_Class when trying to reference pds:Internal_Reference and pds:Local_Internal_Reference
The issue reported seems to be associated with an earlier release of LDDTool. The reported problem could not be duplicated. However on inspection it was discovered that the Assert message was formatted wrong. The message formatting was corrected.
Resolves #391
Refs CCB-256

Issue with DD_Associate_External_Class

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/dd11179.pins

CCB-329 - The aperture attribute is defined for optical instruments with circular light collecting openings. Telescopes at radio wavelengths are not necessarily circular and may be arrays. Broadening the definition will make the attribute more useful at all wavelengths.
Change definition of aperture to: "The aperture attribute provides a measure of the effective collecting area of the telescope -- its diameter (if single and circular) or its equivalent diameter (if non-circular and/or an array).  For purposes of this definition, aperture efficiency is assumed to be 100 percent."
Resolves #403
Refs CCB-329
>

CCB-329 - Broaden Definition of Attribute aperture

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMProcessState.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModelDoc.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSpecification.java

Issue #170 - LDDTool: DocBook generation does not work from any file system location - redux
Looks like lddtool must be run specifically from /path/to/lddtool-11.2.2 in order to generate a DocBook. Lddtool still requires the existence of export/, i.e. it fails if there is no subdirectory export/ in the directory you're running from.
LDDTool now ensures that the directory export/ exists.
Resolves #170

#170 - LDDTool: DocBook generation does not work from any location

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

LDDTool reports a WARNING stating that a new namespace id has been specified, when in fact the namespace had been added to the config.properties file.
Obsolete code was causing the warning to be written. The obsolete code has been removed. Note that the warning was occurring for all LDD namespaces. However the warning was typically not noticed since most LDD runs have numerous warnings.
Resolves #416

#416 - LDDTool: New namespace id has been specified:ml

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/SchemaFileDefn.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java

#418 - Inconsistent naming of JSON schema files
The file name formation rule for the JSON file is not consistent with the rule for other LDDTool generated operational files, for example the XML Schema file, PDS4_PDS_1H00.xsd.
Change the JSON file name from  PDS4_PDS_JSON_1G00.JSON to  PDS4_PDS_1G00.JSON.
Additional minor changes included are:
1) Changed the date format in the JSON file header.
2) Updated the -help description for the -M command line option
Resolves #418

#418 - Inconsistent naming of JSON schema files

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMClass.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ISO11179DOMMDR.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/PermValueDefn.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPontDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOM11179DDPinsFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSpecification.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

Refactor Class information from config to Data Dictionary Protege ontology - Phase 1 - Add Class attributes to dd11179.pins.
The refactoring task focuses on moving the IM class disposition information from an XML configuration file, MDPTNConfigClassDisp.xml, to the IM Protege  metadata registry, dd11179.pins. The class, attribute, and permissible value deprecation information is also being moved from the DMDocument file to dd11179.pins.
Phase 1 of this task simply uploads the updated code to the repository without activating the code. Further testing and a Protege file update will follow.
Resolves #239

Issue #239 - Refactor Class information from config to Data Dictionary Protege ontology - Phase 1

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ISO11179DOMMDR.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/InstDefn.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPontDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOM11179DDPinsFilePClass.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Issue #428 - IMTool Refactoring - Phase 2 - Move deprecated values to Protege ontology file.
This is phase 2 of Issue 306 - Refactor Class information from config to Data Dictionary - This phase focuses on moving deprecation information from the code to the Protege ontology. Also the version identifier for classes and attributes are being moved to the ontology file.
Resolves #428

 Issue #428 - IMTool Refactoring - Phase 2

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSpecification.java

Issue #269 - The PDS4 IM Specification Document is not consistent in the ordering of Permissible Values.
The use of alphabetical order within the IM specification is wide spread. Sometimes, for no obvious reason the convention is dropped which can lead the unwary (read lazy) to oversights.
See Extended Values for: pds:Product_Context/pds:Reference_List/pds:Internal_Reference:
resource_to_target - The resource is associated to a target
target_to_document - The target is associated to a document
target_to_instrument - The target is associated to an instrument
target_to_instrument_host - The target is associated to an instrument_host
Resolves #269

Issue #269 - IM Spec Inconsistent Ordering Permissible Values

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/SchemaFileDefn.java

Issue #431 - Stage the IMTool system for V1.18.0.0 to allow the implementation of approved SCRs and bug fixes.
Had to fix the conversion of the Version Id from 1.18.0.0 to 1I00 for file names.
Resolves #431

#431 - Stage IM V1.18.0.0 - Fix

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

#341 Specify an IngestLDD using a relative path so that I can more easily provide the ingestLDD files to LDDTool.
Given an installed LDDTool and a relative path to one or more IngestLDDs
When I perform lddtool -lpJ <../relative/path/to/IngestLDD>
Then I expect lddtool to generate the IngestLDDs the same as using an absolute path
Resolves #341

#341 Specify an IngestLDD using a relative path

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB-343 - Revise Product_Metadata_Supplemental  Description
The request is to remove the restriction that Product_Metadata_Supplemental may only be associated with one collection. Removing this restriction requires changing text in the description of the class in the IM and associated text in the Standards Reference. This change will improve the effective use of Product_Metadata_Supplemental.
Deprecated code was also removed from XML4LabelSchemaDOM
Resolves #448
Refs CCB-343
For testing the IM Spec can be checked. The class description of Product_Metadata_Supplemental has been changed as per the Request Changes section in the SCR.

CCB-343 - Revise Product_Metadata_Supplemental Desc

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB-335 - Inventory Specification Allows Too Many Delimiters
The request is to add schematron rules to limit the attribute <Inventory.field_delimiter> to one and only one value "Comma" and add additional related constraints. This change will make the IM consistent with the Standards Reference where it states that "Records in the Inventory table [have] two fields, delimited by a single comma."
Resolves #453
Refs CCB-335

CCB-335 - Inventory Specification Allows Too Many Delimiters

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB-339	add Units_of_Power with SI watts as option - Bugfix
@rchenatjpl Fixed the following
1.	Line 528 is
sch:rule context="DD_Value_Domain/pds:unit_of_measure_type" role="warning"
but should be
sch:rule context="pds:DD_Value_Domain/pds:unit_of_measure_type" role="warning"
2.	Lines 532,534,588,590 are missing 'Units_of_Power'
https://pds-jira.jpl.nasa.gov/browse/CCB-339
Add Units_of_Power as a new subclass of Unit_of_Measure. Available values for <unit_id> would be [,prefix]watt and dBm (dB with respect to one milliwatt).
Resolves #443
Refs CCB-339

CCB-339	add Units_of_Power with SI watts as option - Bugfix

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Issue #434 ASCII_Date_Time_* do not sufficiently check valid days of a month or seconds
Per NASA-PDS/harvest#81, it looks like the PDS4 IM schematron rules do not sufficiently check the proper days for each month.
Two new schematron rules were added to address the issue.
Resolves #434

Issue #434 ASCII_Date_Time_* - Schematron

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPontDOMModel.java

Issue #463  LDDTool 14 is not generating against past versions of the IM correctly
The refactoring of Object Class dispositions to the Protege file is not reflected in past versions of the IM. 
To fix the problem, LDDTool runs using past versions of the IM no longer use the Protege files for the class disposition. 
Resolves #463

Issue #463  LDDTool 14 is not generating against past IM versions

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

Issue #459 : LDDTool is not combining Schematron Contexts correctly when adding to an auto-generated context
A bug was found where a schematron rule from an Ingest_LDD file was being written separately instead of being combined with an existing (common) schematron rule for Units of Measure. The bug has been fixed. Before and after files are attached.
The fix consists of merging the assert statement
<sch:assert test="@unit = 'arcsec'">
<title>rule_units_rollover_fwhm/Rule</title>
The rollover_fwhm must have unit = 'arcsec'.</sch:assert>
into the following rule.
sch:pattern
<sch:rule context="survey:Rollover/survey:rollover_fwhm">
<sch:assert test="@Unit = 'arcsec'">
<title>rule_units_rollover_fwhm/Rule</title>
The rollover_fwhm must have unit = 'arcsec'.</sch:assert>
<sch:assert …

Issue #459 : LDDTool is not combining Schematron Contexts

---

model-ontology/src/ontology/Data/UpperModel.pont

Change "schemtron" (misspelling) to "schematron" in limited places in code.
N/A minor correction.
N/A

Correct misspelling of "schematron"

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GenDOMRules.java

Issue #468 : LDDTool is generating multiple Schematron rules to test the same condition
The IngestLDD for the DISP LDD includes <DD_Permissible_Value> for the values “true” and “false”, presumably to provide value meanings for the values of the attributes Movie_Display_Settings/disp:loop_flag and disp:Movie_Display_Settings/disp:loop_back_and_forth_flag, defined as ASCII_Boolean.
Since these attributes each have a set of enumerated values, LDDTool assumes that rules need to be written to validate the enumerated values. However, since the value type is ASCII_Boolean, the values of the attributes are validated using the definition of ASCII_Boolean in the common dictionary. There is no need for both types of validation so a test was added to preclude the writing of rules for attributes of …

Issue #468 : LDDTool is generating multiple duplicate Schematron rules

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB209 - Fix the PDS4 IM class hierarchy
The PDS4 Information Model (IM) has been modified to conform to the Open Archival Information System (OAIS) Reference Model. In particular each entity defined in the IM is now defined as an Information Object, a composite of metadata and a data object. More specifically, each IM entity that describes data is now associated with the defined class, "Digital_Object". This change does not effect the files that are generated for operations, for example the .xsd and .sch files.
Resolves #159
Refs CCB-209

CCB209 - Fix the PDS4 IM class hierarchy

---

model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB-351 - Term Mapping
Bugfix - Added Extended Classes as members of the Ingest_LDD Class
1) Create the classes DD_Attribute_Extended and DD_Class_Extended to allow the mapping between Attributes and Classes respectively. 
2) Construct these classes to be almost identical to the existing DD_Attribute and DD_Class, respectively. 
3) Allow the reference of existing attributes and classes by their XPath. 
4) Allow DD_Attribute_Extended and DD_Class_Extended to be referenced using DD_Association. 
5) These new classes will not be documented externally and not available to Discipline/Mission dictionaries. 
Resolves #503
Refs CCB-351

CCB-351 - Term Mapping - Add Extended Classes to Ingest_LDD

---

model-ontology/src/ontology/Data/1E00/config.properties
model-ontology/src/ontology/Data/1F00/config.properties
model-ontology/src/ontology/Data/1G00/config.properties
model-ontology/src/ontology/Data/1H00/config.properties
model-ontology/src/ontology/Data/1I00/config.properties

Issue #506 : hyb2 has incorrect namespace for IM v1.14
Added "hyb2" to 1E00 and 1F00 after checking all versions of the IM config.properties files back to 1E00.
1.14.0.0 - 1.20 - 1.20 - Build 10b  - 1E00 - null
1.15.0.0 - 1.21 - 1.21 - Build 11.0 - 1F00 - null
1.16.0.0 - 1.22 - 1.22 - Build 11.1 - 1G00 - hyb2
1.17.0.0 - 1.23 - 1.23 - Build 12.0 - 1H00 - hyb2
1.18.0.0 - 1.24 - 1.24 - Build 12.1 - 1I00 - hyb2
1.19.0.0 - 1.25 - 1.25 - Build 13.0 - 1J00 - hyb2
Good sleuthing:
- RChen had a similar issue, described here, which @jshughes addressed in this PR.
- does this have anything to do with the absence of hyb2 in 1E00's config.properties?
Resolves #506

Issue #506 : hyb2 has incorrect namespace for IM v1.14

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/SchemaFileDefn.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/XML4LabelSchemaDOM.java

Issue #507 : Bug generating BepiColombo SERENA dictionary
LDDTool creates namespaces using the namespace id as defined in the Ingest_LDD file. However for PSA namespaces, the namespace id needs to be converted from a single string, to a list of directories. For example the namespace id "bc_mpo_srn" must be replaced with "bc/mpo/srn" for use in the namespace.
http://psa.esa.int/psa/bc/mpo/srn/v1
- instead of - 
http://psa.esa.int/psa/bc_mpo_srn/v1 
Resolves #507
Testing: See attached zip.
input files: Ingest_PDS4_PSA_BC_MPO_SRN_1000.xml
output files:PDS4_BC_MPO_SRN_1J00_1000.xsd
PDS4_BC_MPO_SRN_1J00_1000.sch
[Issue507.zip](https://github.com/NASA-PDS/pds4-information-model/files/9687281/Issue507.zip)

Issue #507 : Bug generating BepiColombo SERENA dictionary

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMAttr.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

LDDTool is not including permissible value in the Data Dictionary DocBook file. The problem only occurs with Type_List style Ingest_LDDs. The problem had not yet appeared in any PDS LDDs but was found in a different project using the same software.
Resolves #580

Issue #580 : LDDTool not including permissible value in DD DocBook file.

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMProp.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/TermEntryDefn.java

Issue #580 : LDDTool not including permissible value in DD DocBook file.
Found and fixed problem with LDDTool output.
Changes to use new value of "local_identifier". Using nameSpace:local_identifier consistently for attributes, classes, and dot.notation e.g.,pds.Internal_Reference
Resolves #580

Issue #580 2 ldd tool not including permissible value in dd doc book file

---

model-dmdocument/pom.xml
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ClassAttrPropClassification.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ClassPropAttr.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ClassPropClass.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ClassPropertiesBase.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ClassPropertiesOWL.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMProcessState.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModelsCustom.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/RelationshipProperties.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBookAnon.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBooks.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMRDFTTLFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMStandardIdExtract.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMTermEntryJSON.java

Issue #467 : Add flags to support generation of TTL/OWL files 
Issue #458 : As a developer I want to have the PDS4 Information Model expressed in the RDF/OWL/TTL format. 
Added "-O" option to export TTL/OWL files from the PDS4 IM. 
The TTL/OWL export conforms to the requirements provided by the JPL Institutional Knowledge Graph (IKG) task.
This RDF file is written using OWL semantics and is in the TTL (turtle) syntax.
This update also includes code clean-up for exporting the terminological mapping file and customized one-off files. The terminological mapping issues remain open.
Test: Use the -O option to generate the OWL/TTL export. Note that the -l option (el for LDDTool) is omitted, i.e., the DMDocument app runs as IMTool not LDDTool and uses only the Common dictionary.
.\bin\DMDOC.bat …

Issue #467 : Add flags to support generation of TTL/OWL files 

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Stage the IMTool system for V1.20.0.0 to allow the implementation of approved SCRs and bug fixes.
Resolves #596
Testing: See attached file.
The IM Specification document and all other generated documents should have the IM Version Id: 1.20.0.0   (1.K.0.0)
[index_1K00.zip](https://github.com/NASA-PDS/pds4-information-model/files/10817283/index_1K00.zip)

Issue #596 - Stage the PDS4 Information Model Version 1.20.0.0 (1.K.0.0)

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Issue #658 : LDDTool does not support IM version 1K00 
Typo - change buildIMVersionFolderId from "1.K.0.0"  to "1K00"
Resolves #658

Issue #658 : LDDTool does not support IM version 1K00 

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java

Issue #661 LDDTool fails for dependent LDDs since v14.2.0
Added code to check local_identifier with colon in addition to dot as namespace delimiter
Resolves #661

Issue #661 LDDTool fails for dependent LDDs since v14.2.0

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMProcessState.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModels.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ExportModelsCustom.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFileLib.java

The JSON Termmap writer has been added to WriteDOMDDJSONFileLib. The original WriteDOMDDJSONFile will be deprecated after successful testing during I&T. WriteDOMDDJSONFileLib is a refactor of WriteDOMDDJSONFile to use the org.json.simple JSON library.
The output from the refactored WriteDOMDDJSONFileLib seems to produce, in general, the same output as the original WriteDOMDDJSONFile. Cosmetic differences are that the JSON output file needs to be “pretty printed” and the “order” of the "names" was not maintained.  
There were a few cases found where a "name" did not exist for a "value". In such cases a "blank node name" was created. The format of the blank node name is "bn#" where # is a sequence number.
Resolves #670
Refs CCB-351

Issue #670 Adds to default output JSON TermMap 

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java

Issue #667 lddtool does not generate the correct closing tag for rule_type = Report
To fix the issue, the closing tag for a Report type rule was changed to sch:report. There was also some minor cleanup of the code.
A test case, a derivation of the DISP LDD, is attached. The test case insert starts at "". Included in the attached is also the resulting .sch file. 
The resulting output should validate correctly instead of throwing an error. More specifically the ending tag should be </sch:report> and not </sch:assert>.
[Issue667.zip](https://github.com/NASA-PDS/pds4-information-model/files/12361718/Issue667.zip)

Issue #667 lddtool does not generate the correct closing tag for rule_type = Report

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetValueMeanings.java
model-ontology/src/ontology/Data/MDPTNConfigClassDisp.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB-336 Add a License_Information class to the Identification_Area 
Add an optional License_Information class to the Identification_Area
The resulting Product_Observational label template should look like the following
<Identification_Area>
<logical_identifier>urn:-:-:-</logical_identifier>
<version_id>0.0</version_id>
<title>title0</title>
<information_model_version>information_model_version0</information_model_version>
<product_class>product_class0</product_class>
...
<License_Information>
<name>name0</name>
<description>description2</description>
<Internal_Reference>
<lid_reference>urn:-:-:-</lid_reference>
<reference_type>reference_type0</reference_type>
<comment>comment1</comment>
</Internal_Reference>
</License_Information>
</Identification_Area>
Resolves #679
Refs CCB-336

Add an optional License_Information class to the Identification_Area

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetValueMeanings.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

CCB-336 Add a License_Information class to the Identification_Area 
Update to add schemtron to validate the reference type in the following products:
Product_Ancillary, Product_Browse, Product_Bundle, Product_Collection, Product_Document, Product_External, Product_File_Text, Product_Metadata_Supplemental, Product_Native, Product_Observational, Product_Context, Product_File_Repository
Resolves #681
Refs CCB-336

Update to add schemtron to validate the reference type in several Product types

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMCSVFileClassHier.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Issue #698  CCB-357: Create Product_External - LID Schematron Rule Update
Updated Product_External LID Schematron rules and asserts as per CCB-357. 
Any Product_External LID must validate against "urn:xxx:yyy:zzz" where xxx, yyy, and zzz are any identifying terms. Four terms are required.
Resolves #698
Refs CCB-357
Testing: The released PDS4_PDS_1L00.sch file should contain the three schematron rules pasted in below.
@rsjoyner can provide test cases.
<sch:pattern>
<sch:rule context="pds:Identification_Area">
<sch:let name="urn_nasa" value="'urn:nasa:pds:'"/>
<sch:let name="urn_esa" value="'urn:esa:psa:'"/>
<sch:let name="urn_ros" value="'urn:ros:rssa:'"/>
<sch:let name="urn_jaxa" value="'urn:jaxa:darts:'"/>
<sch:let name="urn_isro" value="'urn:isro:isda:'"/>
<sch:let name="parentObj" …

Updated Product_External LID Schematron rules as per CCB-357.

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont

Issue #709  Update schematron for agency urn:kari:kpds
The ERROR below is triggered because a new namespace for the Korean PDS had been added but the schematron rule for checking the agency prefixes was not updated. I.e. typically the addition of a new namespace does not require a schematron rule update, except in the case where a new agency is involved. The Schematron rules have been updated.
ERROR  [error.label.schematron]   line 79, 24: The value of the attribute lidvid_reference must start with either: urn:nasa:pds: or urn:esa:psa: or urn:jaxa:darts: or urn:ros:rssa: or urn:isro:isda:
Resolves #709

Update schematron for agency urn:kari:kpds

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMClass.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ISO11179DOMMDR.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPontDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSpecification.java
model-ontology/src/ontology/Data/UpperModel.pins

This PR completes Phase 6 of the IMTool refactoring task, a several month effort that will ultimately allow the deprecation of the MDPTNConfigClassDisp.xml file, the PDS4 Class disposition file (XML format). The Class definition information in MDPTNConfigClassDisp was moved to the dd11179.pins file, a Protege database file based on the ISO 11179 schema and used by IMTool/LDDTool. The dd11179.pins file had been limited to PDS4 Attribute definition information. The dd11179.pins file schema was updated to also capture PDS4 class definition information.
This issue is related to issues #239, #306, #428, and #676. Only phases 1, 2, and 3 resulted in PR requests. Phases 4 and 5 were simply for accounting.
The new output files were DIFFed against the previous output files. The only differences …

IMTool Refactoring Phase 6 - use Protege dd11179.pins for class disposition

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Set THE Product_XML_Schema label version id to 1.0 for all future releases.
Since the IM version id is now part of the Product_XML_Schema label's LID, there is no longer any need to bump the label's VID for each IM release.
The actual change with occur when the IM version id is updated in the config.properties files, for the next release. This update simply updated some documentation.

Updated IM versioning information

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ISO11179DOMMDR.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java

#733 - LDDTool is throwing ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing
When LDDTool ran against any LDDs (e.g. geom) that references common pds: attributes, LDDTool threw "Data Type is missing" errors. Example attributes were pds.name and pds.comment.
The IMTool/LDDTool refactoring task to move class and attribute information to the protege ontology database from external files had not been sufficiently debugged. Three bugs were found and fixed. One error was intermittent and was found to be dependent on sort order.
Why the Maven build example did not catch this error earlier is yet to be determined.
LDDTool runs against valid LDDs will no longer throw "Data Type is missing" errors for common pds: attributes.
Resolves #733

#733 - LDDTool is throwing ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing

---

.github/workflows/branch-cicd.yaml
model-ontology/pom.xml

Plugin executions must now be within `<pluginManagement>` section.
```
$ mvn site
...
[INFO] Rendering 8 report documents
[INFO] Generating "Dependencies" report  --- maven-project-info-reports-plugin:3.5.0:dependencies
[INFO] Generating "Licenses" report      --- maven-project-info-reports-plugin:3.5.0:licenses
[INFO] Generating "Team" report          --- maven-project-info-reports-plugin:3.5.0:team
[INFO] Generating "Summary" report       --- maven-project-info-reports-plugin:3.5.0:summary
[INFO] Generating "Source Code Management" report --- maven-project-info-reports-plugin:3.5.0:scm
[INFO] Generating "Changes" report       --- maven-changes-plugin:2.12.1:changes-report
[WARNING] No issue management URL defined in POM. Links to your issues will not work correctly.
[INFO] Generating …
```

Update maven to support latest java version

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMClass.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPontDOMModel.java

The IMTool/LDDTool code no longer uses the MDPTNConfigClassDisp file and so it can be removed. This file provided various properties for PDS IM classes. These properties have been moved to the Protege database. In addition to removing the file, all code and references associated with the file have been removed.
The software has not been using this file for two builds.  This is simply cleanup.
Resolves #766

Code refactor - Remove THE MDPTNConfigClassDisp file, code and references

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/SchemaFileDefn.java

Removed the Deprecated Objects Array (deprecatedObjects2) from the IMTool/LDDTool source code since this information is now in the Protege database. This was a list of the classes, attributes, and standard  values that had been deprecated since V1.0. 
Also rewrote getCleanVersionId  and getCleanLabelVersionId in the SchemaFileDefn class. This class generates the various version ids and file names used for the generation of the PDS4 stds documents.
There should be no changes in the generated documents. Diffs were performed against previously generated documents 
Resolves #768

Code refactoring and cleanup - Remove deprecated objects2 array

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSchematron.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMSpecification.java
test/smoke-tests.sh

LDDTool does not include all rules from IngestLDD file
Found and fixed the problem in the Schematron (.sch) file writer where the code was not using a unique identifier to reference the Rules defined in IngestLDD.
Test: The missing rules are now written to the Schematron (.sch) file.
The change has caused the order of the rules in the file to changed.
Resolves #771

Fixed problem where LDDTool does not include all rules from IngestLDD

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj
model-ontology/src/ontology/Data/dd11179.pont
model-ontology/src/ontology/Data/dd11179.pprj

CCB-16: Allow micro amps and nano amps as units of current
Added the following units to Units_of_Current
microA - The abbreviated unit for Units_of_Current is microA
nA - The abbreviated unit for Units_of_Current is nA
-Resulting Schema snippet-
<xs:simpleType name="Units_of_Current">
<xs:restriction base="xs:string">
<xs:enumeration value="A"></xs:enumeration>
<xs:enumeration value="mA"></xs:enumeration>
<xs:enumeration value="microA"></xs:enumeration>
<xs:enumeration value="nA"></xs:enumeration>
</xs:restriction>
</xs:simpleType>
Resolves https://github.com/NASA-PDS/pds4-information-model/issues/753
Refs https://github.com/NASA-PDS/PDS4-CCB/issues/16

Added micro amps and nano amps as units of current - CCB-16 - P2

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj

Update the definition of the Units_of_Amount_of_Substance class. 
-    Original: Units_of_Amount_Of_Substance is a magnitude of mass.
-    New: Units_of_Amount_Of_Substance is a magnitude of quantity of chemically unique and identifiable particles (atoms, molecules, ions, etc.). 
No test is necessary. A class  definition was changed.
Resolves #782
Refs NASA-PDS/PDS4-CCB#26

NASA-PDS/PDS4-CCB#26 - Part 2 - Fixed definition of Units_of_Amount_of_Substance

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetValueMeanings.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj

CCB#7  Missing schematron rule to check that Product_Bundle.Target_Identification.Internal_Reference.reference_type is bundle_to_target 
Add the following standard values to allow a bundle to reference a target context product.
Product_Bundle.Context_Area.Target_Identification.Internal_Reference.reference_type == bundle_to_target
Product_Collection.Context_Area.Target_Identification.Internal_Reference.reference_type == collection_to_target
Product_Observational.Observation_Area.Target_Identification.Internal_Reference.reference_type == data_to_target
Product_Browse.Context_Area.Target_Identification.Internal_Reference.reference_type == browse_to_target
Product_External.Context_Area.Target_Identification.Internal_Reference.reference_type == external_to_target …

Add missing standard values for relating a bundle to targets 

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/MasterDOMInfoModel.java
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj

Added a validation rule for geom:kernel_type as a fix for the issue: GEOM LDD schematron rules are not executing as expected <kernel_type> validation #797
Added the geom:kernel_type validation rule to the common dictionary so that it is available for writing to the geom schematron file during LDDTool processing of the Geo Ingest_LDD. The rule is:
<sch:pattern>
<sch:rule context="geom:SPICE_Kernel_Identification/geom:kernel_type">
<sch:assert test=". = ('CK', 'DBK', 'DSK', 'EK', 'FK', 'IK', 'LSK', 'MK', 'PCK', 'SCLK', 'SPK')">
<title>geom:SPICE_Kernel_Identification/geom:kernel_type/kernel_type</title>
The attribute geom:SPICE_Kernel_Identification/geom:kernel_type must be equal to one of the following values 'CK', 'DBK', 'DSK', 'EK', 'FK', 'IK', 'LSK', 'MK', 'PCK', 'SCLK', …

Added geom:kernel_type validation rule

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj
model-ontology/src/ontology/Data/dd11179.pont
model-ontology/src/ontology/Data/dd11179.pprj

Update to #42 Create Array_1D_Spectrum
To complete #42,  the class Array_1D_Spectrum was added to File_Area_Ancillary, File_Area_Browse, and File_Area_Observational_Supplemental. In the original PR, Array_1D_Spectrum was only added to File_Area_Observational.
Test data is available in the attached zip.
[TestingDistributionPackage.zip](https://github.com/user-attachments/files/16785204/TestingDistributionPackage.zip)
Resolves https://github.com/NASA-PDS/PDS4-CCB/issues/42

Add Array_1D_Spectrum to File_Area_Ancillary, File_Area_Browse, and File_Area_Observational_Supplemental

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj
model-ontology/src/ontology/Data/dd11179.pont
model-ontology/src/ontology/Data/dd11179.pprj

Create Array_1D_Spectrum, which would be analogous in every way to Array_2D_Spectrum except that it is a subclass of Array_1D instead of Array_2D. The Array 1D Spectrum class is an extension of the Array 1D class and defines a one dimensional spectrum.
A test label and supporting schema and schematron files are included in the attached zip file
[240826_Array_1D_Spectrum.zip](https://github.com/user-attachments/files/16754807/240826_Array_1D_Spectrum.zip)
Resolves https://github.com/NASA-PDS/PDS4-CCB/issues/42

Create Array_1D_Spectrum 

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj
model-ontology/src/ontology/Data/dd11179.pont
model-ontology/src/ontology/Data/dd11179.pprj

Add value mrad/pixel to Units_of_Pixel_Resolution_Angular
The list of units allowed under Units_of_Pixel_Resolution_Angular needs mrad/pixel for the delivery of data products in which the desired unit is mrad/pixel.
Resolves https://github.com/NASA-PDS/PDS4-CCB/issues/38
A dummy product label and LDD are included in the attached zip file for testing.
[TestingDistributionPackage_38.zip](https://github.com/user-attachments/files/16808459/TestingDistributionPackage_38.zip)

Added mrad/pixel to Units_of_Pixel_Resolution_Angular

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj
model-ontology/src/ontology/Data/dd11179.pont
model-ontology/src/ontology/Data/dd11179.pprj

#24 Reform unit definitions  
Replaced all of the unit_id standard value definitions. The new definitions were provided in the file [UnitReform240808.pdf](https://github.com/user-attachments/files/16551882/UnitReform240808.pdf)
Testing: It is assumed that for definition changes, there is no need for test code. However, the definitions provided were compared to the definitions in the generated PDS4 Information Model Specification. The text of all of the definitions were identical. A zip file containing the two compared files are attached . Note that the definitions for *Deprecated* units of measurement were not changed.
Resolves NASA-PDS/PDS4-CCB#24
[ComparedFiles.zip](https://github.com/user-attachments/files/17194160/ComparedFiles.zip)

Replaced all of the unit_id standard value definitions.

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

#818 Namespace_JUICE_Port_Back_Namespace_Issue.
Fixed the JUICE namespace port-back issue by changing LDDTool to read the configured namespaces from the latest version of the config.properties file, regardless of the -V setting.
Attached is a JUICE Ingest_LDD (PDS4_JUICE_IngestLDD.xml) and two LDDTool run commands. The first run command uses the default config.properties file. The second command uses the -V option to specify version 1J00. The output from both runs are also provided. The Display LDD was used as a test case. The results from these test cases were compared to the released version of the Display schema file.
Resolves https://github.com/NASA-PDS/PDS4-CCB/issues/818
[241024_JUICE_LDDTool_Namespace_LatestConfig_Display.zip](https://github.com/user-attachments/files/17507597/24102 …

Get namespaces from the lastest version of the config.properties file to address the JUICE port-back problem

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/GetValueMeanings.java
model-lddtool/src/test/resources/features/validate.feature
model-lddtool/src/test/resources/github795/bundle.xml
model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj
model-ontology/src/ontology/Data/dd11179.pont
model-ontology/src/ontology/Data/dd11179.pprj

Found and fixed errors in xpath for eight rules.
"Target_Identification/pds:Reference_List/pds:Internal_Reference -> pds:Target_Identification/pds:Internal_Reference
#819  Regression in schematron improvements for references
Fixed problem with schematron rules
#795  CCB-7: Missing schematron rule - bundle_to_targets 
NASA-PDS/PDS4-CCB#7 Missing schematron rule to check that Product_Bundle.Target_Identification.Internal_Reference.reference_type is bundle_to_target
The build test was not successful. However each label in the test suite was loaded into Oxygen. For each " an error was thrown as expected.
Resolves #819
Resolves #795
Refs NASA-PDS/PDS4-CCB#7

Fix regression in schematron improvements for references 

---

model-lddtool/pom.xml
model-lddtool/src/test/java/cucumber/ValidateStepDefs.java
model-lddtool/src/test/resources/features/validate.feature

Check for internal errors and use latest validate
See automated unit testing below or run cucumber tests if not automated yet.
Closes #822

Fix validate misbehavior in cucumber tests

---

model-ontology/src/ontology/Data/UpperModel.pins
model-ontology/src/ontology/Data/UpperModel.pont
model-ontology/src/ontology/Data/UpperModel.pprj
model-ontology/src/ontology/Data/dd11179.pont
model-ontology/src/ontology/Data/dd11179.pprj

Added the following value with its definition to the enumerated list:
W/cm**2/sr/μm
W/cm**2/sr/μm is an abbreviation for watts per square centimeter per steradian per micrometer, which is a unit of spectral radiance (power per unit area per unit solid angle per unit wavelength).
Enclosure contains updates to the IM and a sample (HST) LDD to test the above Requested Changes:
-- updates to IM XSD
-- updates to HST XSD and SCH
-- both VALID and FAIL test cases.
[CCB-47_Units_of_Spectral_Radiance.zip](https://github.com/user-attachments/files/17248440/CCB-47_Units_of_Spectral_Radiance.zip)
Resolves Resolves https://github.com/NASA-PDS/pds4-information-model/issues/830
Refs https://github.com/NASA-PDS/PDS4-CCB/issues/47

CCB-47: Add permissible value to units of spectral radiance

---

pom.xml

This is just to ensure we're using the most recently blessed version of the `gov.nasa.pds` parent project object model (POM).
Note that the new `OSSRH_USERNAME` and `OSSRH_PASSWORD` really ought to be set in the organization—which as of 2024-11-17, they are.
See the equivalent sandbox run at: https://github.com/nasa-pds-engineering-node/pds4-information-model/actions/runs/11881545051
- https://github.com/NASA-PDS/roundup-action/issues/142

Support roundup-action#142 by ensuring we're using the latest gov.nasa.pds parent pom

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

lddtool -v creates/overwrites output directory and files
The -v option should only return the following four lines. The extraneous information is no longer being printed.
LDDTool Version: 
Built with IM Version: 
Build Date: 
Configured IM Versions:
lddtool -v
-- output--
LDDTool Version: ${project.version}
Built with IM Version: 1.23.0.0
Build Date: ${buildNumber}
Configured IM Versions: [1N00, 1M00, 1L00, 1K00, 1J00, 1I00, 1H00, 1G00, 1F00, 1E00, 1D00, 1C00, 1B10, 1B00]
>>  INFO Exit(0)
Resolves #848

Fix bug where `lddtool -v` creates/overwrites output directory and files

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java

Per #849, fixed output from `lddtool --help`
```
$ lddtool --help
usage: LDDTool [-h] [-p] [-l] [-d] [-D] [-J] [-m] [-M] [-n] [-N] [-1] [-T] [-O] [-o] [-C] [-v]
[-V {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}]
[fileNameArr [fileNameArr ...]]
LDDTool process control:
positional arguments:
fileNameArr            Ingest_LDD files to process.
named arguments:
-h, --help             show this help message and exit
-p, --PDS4 processing  Set the context to PDS4 (default: false)
-l, --LDD              Process one or more local data dictionary input files (default: false)
-d, --discipline       Omit the term "mission" from  the  namespace of a dictionary (default:
false)
-D, --DataDict         Write the Data Dictionary DocBook file (default: false)
-J, --JSON …
```

Fix `lddtool --help` output

---

model-ontology/src/ontology/Data/1C00/dd11179.pont
model-ontology/src/ontology/Data/1C00/dd11179.pprj
model-ontology/src/ontology/Data/1D00/dd11179.pont
model-ontology/src/ontology/Data/1D00/dd11179.pprj
model-ontology/src/ontology/Data/1E00/dd11179.pont
model-ontology/src/ontology/Data/1E00/dd11179.pprj

Added missing classes and attributes to dd11179 protege files for releases 1C00, 1D00, and 1E00. 
The problem was that the "dd11179.pins" protege file did not include classes that had been defined in the UpperModel for the following releases,  
1E00 - 1.14.00
1D00 - 1.13.00
1C00 - 1.12.00
Note: Even though only the file "dd11179.pins" was updated the files "dd11179.pprj" and "dd11179.pont" were added since all three flies are now released at each build. All three files are required to open the project in protege.
LDDTool output log for 1.14.00 had no errors. Similarly for 1.13.00 and 1.12.00.
>>  INFO LDDTOOL Version: ${project.version}
>>  INFO IM Version Id: 1.14.0.0
>>  INFO IM Namespace Id: pds
>>  INFO IM Label Version Id: 1.20
>>  INFO Date: Wed Dec 18 19:31:13 EST 2024
>>  INFO …

Fix bug in LDDTool for generating LDDs for 1C00, 1D00, and 1E00

---

.github/workflows/secrets-detection.yaml
.secrets.baseline
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMProcessState.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

The -V flag does not work when attempting to generate core IM.
The -V flag for specifying that LDDTool should use a prior version of the IM did not work when generating the Core schemas. The code was changed to allow the -V option for Core and LDD processing.
The WriteDOMDocBook.java was also modified. References to static variables were removed and replaced with get method calls. There was also significant cleanup of dated code.
The regressions tests for comparing current and prior results from LDDTool process will test some of the current changes. A subsequent PR is planned to add additional tests.
Resolves #859
Rebased version of #871

`--V` flag option does not work when attempting to generate core IM

---

model-lddtool/src/test/resources/features/validate.feature

Numerous tests were commented out because validate had a bug where it could not handle running after it loaded LDDs. [with that being fixed here](https://github.com/NASA-PDS/validate/issues/1105), we can add these tests back.
See test run
Fixes #866

Add tests back that use LDDs

---

model-ontology/src/ontology/Data/1C00/UpperModel.pins
model-ontology/src/ontology/Data/1C00/UpperModel.pont
model-ontology/src/ontology/Data/1C00/UpperModel.pprj
model-ontology/src/ontology/Data/1C00/dd11179.pont
model-ontology/src/ontology/Data/1C00/dd11179.pprj

Updated 1C00 protege files to correct class order problem.
To correct the 1C00 XML Schema element ordering problem, the original 1C00 protege files were reprocessed using an archived version of LDDTool (DMDocument.jar). The ordering was corrected. However, additional changes were required a) deprecate two unused classes and b) reset all deprecated items flags. 
The build and existing Cucumber tests that identified this problem seemed to succeed.
Resolves #874

Updated 1C00 protege files to correct class order problem

---

model-lddtool/src/test/resources/features/validate.feature
model-ontology/src/ontology/Data/1D00/UpperModel.pins
model-ontology/src/ontology/Data/1D00/UpperModel.pont
model-ontology/src/ontology/Data/1D00/UpperModel.pprj
model-ontology/src/ontology/Data/1D00/dd11179.pont
model-ontology/src/ontology/Data/1D00/dd11179.pprj

Fixed problem where lddtool -V flag outputs invalid schemas for 1D00 - # 885
Removed DD_Associate_External_Class and reset the deprecated item flags in the Protege database for IM V 1.13.0.0 - 1D00.
A "diff" between a 2019 schema and the new schema identified differences in the commented "Deprecated" items at the end of the XML Schema file. The deprecated flags had to be reset. However, after the modifications, the differences still exist since LDDTool had been modified after the release of 1D00 to alphabetize the deprecated list. 
Maven built successfully. 
A "diff" between the 2019 schema and the new schema did not indicate any differences.
It is assume that there is an existing Cucumber test that found this error. 
Resolves # 885

lddtool -V flag outputs invalid schemas for 1D00

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMProcessState.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFileLib.java

#723 lddtool json export seems to export the whole IM, not just the current dictionary
The "-J" option (export to JSON formatted file) now has three possible outputs. The additional option --include-all-namespaces was added to indicate that all LDDs in the LDDTool run were to be exported to the JSON formatted file.
1. if LDDTool is run with the "-l -J" options, i.e. an LDD run, then only the primary LDD namespace is exported
2. if LDDTool is run with the "-l -J --include-all-namespaces" options, then all LDD namespaces in the run are exported
3. if LDDTool is run with the "-J" option, then only the Common namespace is exported to JSON
1 - java"  -Ddata.home=.../Document/Data -jar "...\DMDocument.jar" -lpJD PDS4_CART_IngestLDD.xml PDS4_CTLI_IngestLDD.xml PDS4_DISP_IngestLDD.xml …

Added --include-all-namespaces option for JSON export

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java
model-lddtool/pom.xml

Generated LDD documentation does not handle xs:choice right
In the PDS4 Data Dictionary, the classes and attributes that are members of choice blocks were not indicated as members of a choice block. The choice blocks are now detected and a "Choice" indicator was added to the cardinality cell in the table.
The following 19 classes and attributes, identified as being members of choice blocks, now have a "Choice" indicator in the associated cardinality cell of the dictionary document. 
Bundle_Member_Entry
Internal_Reference
Product_Context
Record_Binary
Record_Character
Record_Delimited
Citation_Information
Document
File_Area_Ancillary
File_Area_Browse
File_Area_Metadata
File_Area_Native
File_Area_Observational
File_Area_Observational_Supplemental
Group_Field_Binary
Group_Field_Character …

Generated LDD documentation does not handle xs:choice right

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DMDocument.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/DOMUnit.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/LDDDOMParser.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/ProtPontDOMModel.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/SchemaFileDefn.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOM11179DDRDFFile.java
model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDocBook.java

As a user, I want to easily identify which IM and LDD version the WebHelp documentation is for #939
Modified the DocBook writer to include the IM version id for each class and attribute definition. Also fixed a problem with class and attribute version ids. 
The attached snippet from the generated DocBook files shows the IM version id in class and attribute definitions.
[array.pdf](https://github.com/user-attachments/files/21799801/array.pdf)
Resolves #939

Added the IM Version Id to Class and Attribute definitions in the Webhelp documentation

---

model-dmdocument/src/main/java/gov/nasa/pds/model/plugin/WriteDOMDDJSONFileLib.java

LDD generator is not generating valid LDDs
Updated WriteDOMDDJSONFileLib to use attributeId or classId as the array name in Associations
Updated WriteDOMDDJSONFileLib to use "attributeId" or "classId" as the array name in Associations. The name had previously been set to "null" for both. These arrays identify the respective member attributes or classes.
The JSON files before and after the change were compared. The results showed that the array names were no longer "null". The attached zip file contains the two JSON files and a capture image of the comparison.
Resolves #947

Fix issue LDD generator is not generating valid LDDs
